// Code generated by ent, DO NOT EDIT.

package serie

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the serie type in the database.
	Label = "serie"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldHidden holds the string denoting the hidden field in the database.
	FieldHidden = "hidden"
	// FieldLastUpdate holds the string denoting the last_update field in the database.
	FieldLastUpdate = "last_update"
	// EdgeItems holds the string denoting the items edge name in mutations.
	EdgeItems = "items"
	// EdgeFavoriteOfUser holds the string denoting the favorite_of_user edge name in mutations.
	EdgeFavoriteOfUser = "favorite_of_user"
	// Table holds the table name of the serie in the database.
	Table = "series"
	// ItemsTable is the table that holds the items relation/edge.
	ItemsTable = "meta"
	// ItemsInverseTable is the table name for the Meta entity.
	// It exists in this package in order to avoid circular dependency with the "meta" package.
	ItemsInverseTable = "meta"
	// ItemsColumn is the table column denoting the items relation/edge.
	ItemsColumn = "meta_serie"
	// FavoriteOfUserTable is the table that holds the favorite_of_user relation/edge. The primary key declared below.
	FavoriteOfUserTable = "user_favorite_series"
	// FavoriteOfUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	FavoriteOfUserInverseTable = "users"
)

// Columns holds all SQL columns for serie fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldHidden,
	FieldLastUpdate,
}

var (
	// FavoriteOfUserPrimaryKey and FavoriteOfUserColumn2 are the table columns denoting the
	// primary key for the favorite_of_user relation (M2M).
	FavoriteOfUserPrimaryKey = []string{"user_id", "serie_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultHidden holds the default value on creation for the "hidden" field.
	DefaultHidden bool
	// DefaultLastUpdate holds the default value on creation for the "last_update" field.
	DefaultLastUpdate func() time.Time
)

// OrderOption defines the ordering options for the Serie queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByHidden orders the results by the hidden field.
func ByHidden(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHidden, opts...).ToFunc()
}

// ByLastUpdate orders the results by the last_update field.
func ByLastUpdate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdate, opts...).ToFunc()
}

// ByItemsCount orders the results by items count.
func ByItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newItemsStep(), opts...)
	}
}

// ByItems orders the results by items terms.
func ByItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFavoriteOfUserCount orders the results by favorite_of_user count.
func ByFavoriteOfUserCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFavoriteOfUserStep(), opts...)
	}
}

// ByFavoriteOfUser orders the results by favorite_of_user terms.
func ByFavoriteOfUser(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFavoriteOfUserStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ItemsTable, ItemsColumn),
	)
}
func newFavoriteOfUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FavoriteOfUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, FavoriteOfUserTable, FavoriteOfUserPrimaryKey...),
	)
}
