// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: browse.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter int32

const (
	Filter_FILTER_UNKNOWN        Filter = 0
	Filter_FILTER_FAVORITE_ITEMS Filter = 1
	Filter_FILTER_FAVORITE_TAGS  Filter = 2
)

// Enum value maps for Filter.
var (
	Filter_name = map[int32]string{
		0: "FILTER_UNKNOWN",
		1: "FILTER_FAVORITE_ITEMS",
		2: "FILTER_FAVORITE_TAGS",
	}
	Filter_value = map[string]int32{
		"FILTER_UNKNOWN":        0,
		"FILTER_FAVORITE_ITEMS": 1,
		"FILTER_FAVORITE_TAGS":  2,
	}
)

func (x Filter) Enum() *Filter {
	p := new(Filter)
	*p = x
	return p
}

func (x Filter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter) Descriptor() protoreflect.EnumDescriptor {
	return file_browse_proto_enumTypes[0].Descriptor()
}

func (Filter) Type() protoreflect.EnumType {
	return &file_browse_proto_enumTypes[0]
}

func (x Filter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter.Descriptor instead.
func (Filter) EnumDescriptor() ([]byte, []int) {
	return file_browse_proto_rawDescGZIP(), []int{0}
}

type SortField int32

const (
	SortField_SORT_FIELD_NAME          SortField = 0
	SortField_SORT_FIELD_CREATION_TIME SortField = 1
	SortField_SORT_FIELD_PAGECOUNT     SortField = 2
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SORT_FIELD_NAME",
		1: "SORT_FIELD_CREATION_TIME",
		2: "SORT_FIELD_PAGECOUNT",
	}
	SortField_value = map[string]int32{
		"SORT_FIELD_NAME":          0,
		"SORT_FIELD_CREATION_TIME": 1,
		"SORT_FIELD_PAGECOUNT":     2,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_browse_proto_enumTypes[1].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_browse_proto_enumTypes[1]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_browse_proto_rawDescGZIP(), []int{1}
}

type SortOrder int32

const (
	SortOrder_SORT_ORDER_ASCENDING  SortOrder = 0
	SortOrder_SORT_ORDER_DESCENDING SortOrder = 1
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_ASCENDING",
		1: "SORT_ORDER_DESCENDING",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_ASCENDING":  0,
		"SORT_ORDER_DESCENDING": 1,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_browse_proto_enumTypes[2].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_browse_proto_enumTypes[2]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_browse_proto_rawDescGZIP(), []int{2}
}

type BrowseListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Filter        Filter                 `protobuf:"varint,3,opt,name=Filter,proto3,enum=Filter" json:"Filter,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty"`
	ItemPerPage   int32                  `protobuf:"varint,5,opt,name=ItemPerPage,proto3" json:"ItemPerPage,omitempty"`
	Search        string                 `protobuf:"bytes,6,opt,name=Search,proto3" json:"Search,omitempty"`
	Sort          SortField              `protobuf:"varint,7,opt,name=Sort,proto3,enum=SortField" json:"Sort,omitempty"`
	Order         SortOrder              `protobuf:"varint,8,opt,name=Order,proto3,enum=SortOrder" json:"Order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseListRequest) Reset() {
	*x = BrowseListRequest{}
	mi := &file_browse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseListRequest) ProtoMessage() {}

func (x *BrowseListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseListRequest.ProtoReflect.Descriptor instead.
func (*BrowseListRequest) Descriptor() ([]byte, []int) {
	return file_browse_proto_rawDescGZIP(), []int{0}
}

func (x *BrowseListRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BrowseListRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BrowseListRequest) GetFilter() Filter {
	if x != nil {
		return x.Filter
	}
	return Filter_FILTER_UNKNOWN
}

func (x *BrowseListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BrowseListRequest) GetItemPerPage() int32 {
	if x != nil {
		return x.ItemPerPage
	}
	return 0
}

func (x *BrowseListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *BrowseListRequest) GetSort() SortField {
	if x != nil {
		return x.Sort
	}
	return SortField_SORT_FIELD_NAME
}

func (x *BrowseListRequest) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_SORT_ORDER_ASCENDING
}

type BrowseListResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TagFavorite   bool                      `protobuf:"varint,1,opt,name=TagFavorite,proto3" json:"TagFavorite,omitempty"`
	TotalPage     int32                     `protobuf:"varint,2,opt,name=TotalPage,proto3" json:"TotalPage,omitempty"`
	Items         []*BrowseListResponseItem `protobuf:"bytes,3,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseListResponse) Reset() {
	*x = BrowseListResponse{}
	mi := &file_browse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseListResponse) ProtoMessage() {}

func (x *BrowseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseListResponse.ProtoReflect.Descriptor instead.
func (*BrowseListResponse) Descriptor() ([]byte, []int) {
	return file_browse_proto_rawDescGZIP(), []int{1}
}

func (x *BrowseListResponse) GetTagFavorite() bool {
	if x != nil {
		return x.TagFavorite
	}
	return false
}

func (x *BrowseListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *BrowseListResponse) GetItems() []*BrowseListResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BrowseListResponseItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IsFavorite     bool                   `protobuf:"varint,3,opt,name=IsFavorite,proto3" json:"IsFavorite,omitempty"`
	IsRead         bool                   `protobuf:"varint,4,opt,name=IsRead,proto3" json:"IsRead,omitempty"`
	PageCount      int32                  `protobuf:"varint,5,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	HasFavoriteTag bool                   `protobuf:"varint,6,opt,name=HasFavoriteTag,proto3" json:"HasFavoriteTag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BrowseListResponseItem) Reset() {
	*x = BrowseListResponseItem{}
	mi := &file_browse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseListResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseListResponseItem) ProtoMessage() {}

func (x *BrowseListResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_browse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseListResponseItem.ProtoReflect.Descriptor instead.
func (*BrowseListResponseItem) Descriptor() ([]byte, []int) {
	return file_browse_proto_rawDescGZIP(), []int{2}
}

func (x *BrowseListResponseItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrowseListResponseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrowseListResponseItem) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *BrowseListResponseItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *BrowseListResponseItem) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *BrowseListResponseItem) GetHasFavoriteTag() bool {
	if x != nil {
		return x.HasFavoriteTag
	}
	return false
}

type BrowseThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseThumbnailRequest) Reset() {
	*x = BrowseThumbnailRequest{}
	mi := &file_browse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseThumbnailRequest) ProtoMessage() {}

func (x *BrowseThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseThumbnailRequest.ProtoReflect.Descriptor instead.
func (*BrowseThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_browse_proto_rawDescGZIP(), []int{3}
}

func (x *BrowseThumbnailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BrowseThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseThumbnailResponse) Reset() {
	*x = BrowseThumbnailResponse{}
	mi := &file_browse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseThumbnailResponse) ProtoMessage() {}

func (x *BrowseThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseThumbnailResponse.ProtoReflect.Descriptor instead.
func (*BrowseThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_browse_proto_rawDescGZIP(), []int{4}
}

func (x *BrowseThumbnailResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BrowseThumbnailResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_browse_proto protoreflect.FileDescriptor

const file_browse_proto_rawDesc = "" +
	"\n" +
	"\fbrowse.proto\"\xea\x01\n" +
	"\x11BrowseListRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x10\n" +
	"\x03Tag\x18\x02 \x01(\tR\x03Tag\x12\x1f\n" +
	"\x06Filter\x18\x03 \x01(\x0e2\a.FilterR\x06Filter\x12\x12\n" +
	"\x04Page\x18\x04 \x01(\x05R\x04Page\x12 \n" +
	"\vItemPerPage\x18\x05 \x01(\x05R\vItemPerPage\x12\x16\n" +
	"\x06Search\x18\x06 \x01(\tR\x06Search\x12\x1e\n" +
	"\x04Sort\x18\a \x01(\x0e2\n" +
	".SortFieldR\x04Sort\x12 \n" +
	"\x05Order\x18\b \x01(\x0e2\n" +
	".SortOrderR\x05Order\"\x83\x01\n" +
	"\x12BrowseListResponse\x12 \n" +
	"\vTagFavorite\x18\x01 \x01(\bR\vTagFavorite\x12\x1c\n" +
	"\tTotalPage\x18\x02 \x01(\x05R\tTotalPage\x12-\n" +
	"\x05Items\x18\x03 \x03(\v2\x17.BrowseListResponseItemR\x05Items\"\xba\x01\n" +
	"\x16BrowseListResponseItem\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"IsFavorite\x18\x03 \x01(\bR\n" +
	"IsFavorite\x12\x16\n" +
	"\x06IsRead\x18\x04 \x01(\bR\x06IsRead\x12\x1c\n" +
	"\tPageCount\x18\x05 \x01(\x05R\tPageCount\x12&\n" +
	"\x0eHasFavoriteTag\x18\x06 \x01(\bR\x0eHasFavoriteTag\",\n" +
	"\x16BrowseThumbnailRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"O\n" +
	"\x17BrowseThumbnailResponse\x12 \n" +
	"\vContentType\x18\x01 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data*Q\n" +
	"\x06Filter\x12\x12\n" +
	"\x0eFILTER_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15FILTER_FAVORITE_ITEMS\x10\x01\x12\x18\n" +
	"\x14FILTER_FAVORITE_TAGS\x10\x02*X\n" +
	"\tSortField\x12\x13\n" +
	"\x0fSORT_FIELD_NAME\x10\x00\x12\x1c\n" +
	"\x18SORT_FIELD_CREATION_TIME\x10\x01\x12\x18\n" +
	"\x14SORT_FIELD_PAGECOUNT\x10\x02*@\n" +
	"\tSortOrder\x12\x18\n" +
	"\x14SORT_ORDER_ASCENDING\x10\x00\x12\x19\n" +
	"\x15SORT_ORDER_DESCENDING\x10\x012}\n" +
	"\x06Browse\x121\n" +
	"\x04List\x12\x12.BrowseListRequest\x1a\x13.BrowseListResponse\"\x00\x12@\n" +
	"\tThumbnail\x12\x17.BrowseThumbnailRequest\x1a\x18.BrowseThumbnailResponse\"\x00B-Z+github.com/mangaweb4/mangaweb4-backend/grpcb\x06proto3"

var (
	file_browse_proto_rawDescOnce sync.Once
	file_browse_proto_rawDescData []byte
)

func file_browse_proto_rawDescGZIP() []byte {
	file_browse_proto_rawDescOnce.Do(func() {
		file_browse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_browse_proto_rawDesc), len(file_browse_proto_rawDesc)))
	})
	return file_browse_proto_rawDescData
}

var file_browse_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_browse_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_browse_proto_goTypes = []any{
	(Filter)(0),                     // 0: Filter
	(SortField)(0),                  // 1: SortField
	(SortOrder)(0),                  // 2: SortOrder
	(*BrowseListRequest)(nil),       // 3: BrowseListRequest
	(*BrowseListResponse)(nil),      // 4: BrowseListResponse
	(*BrowseListResponseItem)(nil),  // 5: BrowseListResponseItem
	(*BrowseThumbnailRequest)(nil),  // 6: BrowseThumbnailRequest
	(*BrowseThumbnailResponse)(nil), // 7: BrowseThumbnailResponse
}
var file_browse_proto_depIdxs = []int32{
	0, // 0: BrowseListRequest.Filter:type_name -> Filter
	1, // 1: BrowseListRequest.Sort:type_name -> SortField
	2, // 2: BrowseListRequest.Order:type_name -> SortOrder
	5, // 3: BrowseListResponse.Items:type_name -> BrowseListResponseItem
	3, // 4: Browse.List:input_type -> BrowseListRequest
	6, // 5: Browse.Thumbnail:input_type -> BrowseThumbnailRequest
	4, // 6: Browse.List:output_type -> BrowseListResponse
	7, // 7: Browse.Thumbnail:output_type -> BrowseThumbnailResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_browse_proto_init() }
func file_browse_proto_init() {
	if File_browse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_browse_proto_rawDesc), len(file_browse_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_browse_proto_goTypes,
		DependencyIndexes: file_browse_proto_depIdxs,
		EnumInfos:         file_browse_proto_enumTypes,
		MessageInfos:      file_browse_proto_msgTypes,
	}.Build()
	File_browse_proto = out.File
	file_browse_proto_goTypes = nil
	file_browse_proto_depIdxs = nil
}
