// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: manga.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MangaListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Filter        Filter                 `protobuf:"varint,3,opt,name=Filter,proto3,enum=mangaweb4.types.Filter" json:"Filter,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty"`
	ItemPerPage   int32                  `protobuf:"varint,5,opt,name=ItemPerPage,proto3" json:"ItemPerPage,omitempty"`
	Search        string                 `protobuf:"bytes,6,opt,name=Search,proto3" json:"Search,omitempty"`
	Sort          SortField              `protobuf:"varint,7,opt,name=Sort,proto3,enum=mangaweb4.types.SortField" json:"Sort,omitempty"`
	Order         SortOrder              `protobuf:"varint,8,opt,name=Order,proto3,enum=mangaweb4.types.SortOrder" json:"Order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaListRequest) Reset() {
	*x = MangaListRequest{}
	mi := &file_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaListRequest) ProtoMessage() {}

func (x *MangaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaListRequest.ProtoReflect.Descriptor instead.
func (*MangaListRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{0}
}

func (x *MangaListRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MangaListRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MangaListRequest) GetFilter() Filter {
	if x != nil {
		return x.Filter
	}
	return Filter_FILTER_UNKNOWN
}

func (x *MangaListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MangaListRequest) GetItemPerPage() int32 {
	if x != nil {
		return x.ItemPerPage
	}
	return 0
}

func (x *MangaListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *MangaListRequest) GetSort() SortField {
	if x != nil {
		return x.Sort
	}
	return SortField_SORT_FIELD_NAME
}

func (x *MangaListRequest) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_SORT_ORDER_ASCENDING
}

type MangaListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TagFavorite   bool                     `protobuf:"varint,1,opt,name=TagFavorite,proto3" json:"TagFavorite,omitempty"`
	TotalPage     int32                    `protobuf:"varint,2,opt,name=TotalPage,proto3" json:"TotalPage,omitempty"`
	Items         []*MangaListResponseItem `protobuf:"bytes,3,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaListResponse) Reset() {
	*x = MangaListResponse{}
	mi := &file_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaListResponse) ProtoMessage() {}

func (x *MangaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaListResponse.ProtoReflect.Descriptor instead.
func (*MangaListResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{1}
}

func (x *MangaListResponse) GetTagFavorite() bool {
	if x != nil {
		return x.TagFavorite
	}
	return false
}

func (x *MangaListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *MangaListResponse) GetItems() []*MangaListResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MangaListResponseItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IsFavorite     bool                   `protobuf:"varint,3,opt,name=IsFavorite,proto3" json:"IsFavorite,omitempty"`
	IsRead         bool                   `protobuf:"varint,4,opt,name=IsRead,proto3" json:"IsRead,omitempty"`
	PageCount      int32                  `protobuf:"varint,5,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	HasFavoriteTag bool                   `protobuf:"varint,6,opt,name=HasFavoriteTag,proto3" json:"HasFavoriteTag,omitempty"`
	CurrentPage    int32                  `protobuf:"varint,7,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	MaxProgress    int32                  `protobuf:"varint,8,opt,name=MaxProgress,proto3" json:"MaxProgress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MangaListResponseItem) Reset() {
	*x = MangaListResponseItem{}
	mi := &file_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaListResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaListResponseItem) ProtoMessage() {}

func (x *MangaListResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaListResponseItem.ProtoReflect.Descriptor instead.
func (*MangaListResponseItem) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{2}
}

func (x *MangaListResponseItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MangaListResponseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MangaListResponseItem) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *MangaListResponseItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MangaListResponseItem) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *MangaListResponseItem) GetHasFavoriteTag() bool {
	if x != nil {
		return x.HasFavoriteTag
	}
	return false
}

func (x *MangaListResponseItem) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *MangaListResponseItem) GetMaxProgress() int32 {
	if x != nil {
		return x.MaxProgress
	}
	return 0
}

type MangaThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaThumbnailRequest) Reset() {
	*x = MangaThumbnailRequest{}
	mi := &file_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaThumbnailRequest) ProtoMessage() {}

func (x *MangaThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaThumbnailRequest.ProtoReflect.Descriptor instead.
func (*MangaThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{3}
}

func (x *MangaThumbnailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MangaThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaThumbnailResponse) Reset() {
	*x = MangaThumbnailResponse{}
	mi := &file_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaThumbnailResponse) ProtoMessage() {}

func (x *MangaThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaThumbnailResponse.ProtoReflect.Descriptor instead.
func (*MangaThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{4}
}

func (x *MangaThumbnailResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MangaThumbnailResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MangaDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaDetailRequest) Reset() {
	*x = MangaDetailRequest{}
	mi := &file_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaDetailRequest) ProtoMessage() {}

func (x *MangaDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaDetailRequest.ProtoReflect.Descriptor instead.
func (*MangaDetailRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{5}
}

func (x *MangaDetailRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MangaDetailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MangaDetailResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Name          string                        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Favorite      bool                          `protobuf:"varint,2,opt,name=Favorite,proto3" json:"Favorite,omitempty"`
	PageCount     int32                         `protobuf:"varint,3,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	CurrentPage   int32                         `protobuf:"varint,4,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	Tags          []*MangaDetailResponseTagItem `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaDetailResponse) Reset() {
	*x = MangaDetailResponse{}
	mi := &file_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaDetailResponse) ProtoMessage() {}

func (x *MangaDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaDetailResponse.ProtoReflect.Descriptor instead.
func (*MangaDetailResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{6}
}

func (x *MangaDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MangaDetailResponse) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

func (x *MangaDetailResponse) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *MangaDetailResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *MangaDetailResponse) GetTags() []*MangaDetailResponseTagItem {
	if x != nil {
		return x.Tags
	}
	return nil
}

type MangaDetailResponseTagItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IsFavorite    bool                   `protobuf:"varint,3,opt,name=IsFavorite,proto3" json:"IsFavorite,omitempty"`
	IsHidden      bool                   `protobuf:"varint,4,opt,name=IsHidden,proto3" json:"IsHidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaDetailResponseTagItem) Reset() {
	*x = MangaDetailResponseTagItem{}
	mi := &file_manga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaDetailResponseTagItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaDetailResponseTagItem) ProtoMessage() {}

func (x *MangaDetailResponseTagItem) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaDetailResponseTagItem.ProtoReflect.Descriptor instead.
func (*MangaDetailResponseTagItem) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{7}
}

func (x *MangaDetailResponseTagItem) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MangaDetailResponseTagItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MangaDetailResponseTagItem) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *MangaDetailResponseTagItem) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

type MangaSetFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Favorite      bool                   `protobuf:"varint,3,opt,name=Favorite,proto3" json:"Favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaSetFavoriteRequest) Reset() {
	*x = MangaSetFavoriteRequest{}
	mi := &file_manga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaSetFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaSetFavoriteRequest) ProtoMessage() {}

func (x *MangaSetFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaSetFavoriteRequest.ProtoReflect.Descriptor instead.
func (*MangaSetFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{8}
}

func (x *MangaSetFavoriteRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MangaSetFavoriteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MangaSetFavoriteRequest) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type MangaSetFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Favorite      bool                   `protobuf:"varint,2,opt,name=Favorite,proto3" json:"Favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaSetFavoriteResponse) Reset() {
	*x = MangaSetFavoriteResponse{}
	mi := &file_manga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaSetFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaSetFavoriteResponse) ProtoMessage() {}

func (x *MangaSetFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaSetFavoriteResponse.ProtoReflect.Descriptor instead.
func (*MangaSetFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{9}
}

func (x *MangaSetFavoriteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MangaSetFavoriteResponse) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type MangaUpdateCoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=X,proto3" json:"X,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=Y,proto3" json:"Y,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=Width,proto3" json:"Width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=Height,proto3" json:"Height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaUpdateCoverRequest) Reset() {
	*x = MangaUpdateCoverRequest{}
	mi := &file_manga_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaUpdateCoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaUpdateCoverRequest) ProtoMessage() {}

func (x *MangaUpdateCoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaUpdateCoverRequest.ProtoReflect.Descriptor instead.
func (*MangaUpdateCoverRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{10}
}

func (x *MangaUpdateCoverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MangaUpdateCoverRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MangaUpdateCoverRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MangaUpdateCoverRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MangaUpdateCoverRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MangaUpdateCoverRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type MangaUpdateCoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaUpdateCoverResponse) Reset() {
	*x = MangaUpdateCoverResponse{}
	mi := &file_manga_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaUpdateCoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaUpdateCoverResponse) ProtoMessage() {}

func (x *MangaUpdateCoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaUpdateCoverResponse.ProtoReflect.Descriptor instead.
func (*MangaUpdateCoverResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{11}
}

func (x *MangaUpdateCoverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MangaPageImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=Width,proto3" json:"Width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaPageImageRequest) Reset() {
	*x = MangaPageImageRequest{}
	mi := &file_manga_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaPageImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaPageImageRequest) ProtoMessage() {}

func (x *MangaPageImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaPageImageRequest.ProtoReflect.Descriptor instead.
func (*MangaPageImageRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{12}
}

func (x *MangaPageImageRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MangaPageImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MangaPageImageRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MangaPageImageRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MangaPageImageRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type MangaPageImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaPageImageResponse) Reset() {
	*x = MangaPageImageResponse{}
	mi := &file_manga_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaPageImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaPageImageResponse) ProtoMessage() {}

func (x *MangaPageImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaPageImageResponse.ProtoReflect.Descriptor instead.
func (*MangaPageImageResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{13}
}

func (x *MangaPageImageResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MangaPageImageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MangaPageImageStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaPageImageStreamResponse) Reset() {
	*x = MangaPageImageStreamResponse{}
	mi := &file_manga_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaPageImageStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaPageImageStreamResponse) ProtoMessage() {}

func (x *MangaPageImageStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaPageImageStreamResponse.ProtoReflect.Descriptor instead.
func (*MangaPageImageStreamResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{14}
}

func (x *MangaPageImageStreamResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MangaPageImageStreamResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MangaPageImageStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MangaPageImageStreamResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MangaRepairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaRepairRequest) Reset() {
	*x = MangaRepairRequest{}
	mi := &file_manga_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaRepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaRepairRequest) ProtoMessage() {}

func (x *MangaRepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaRepairRequest.ProtoReflect.Descriptor instead.
func (*MangaRepairRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{15}
}

func (x *MangaRepairRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MangaRepairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IsSuccess     bool                   `protobuf:"varint,2,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaRepairResponse) Reset() {
	*x = MangaRepairResponse{}
	mi := &file_manga_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaRepairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaRepairResponse) ProtoMessage() {}

func (x *MangaRepairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaRepairResponse.ProtoReflect.Descriptor instead.
func (*MangaRepairResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{16}
}

func (x *MangaRepairResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MangaRepairResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type MangaDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaDownloadRequest) Reset() {
	*x = MangaDownloadRequest{}
	mi := &file_manga_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaDownloadRequest) ProtoMessage() {}

func (x *MangaDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaDownloadRequest.ProtoReflect.Descriptor instead.
func (*MangaDownloadRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{17}
}

func (x *MangaDownloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MangaDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaDownloadResponse) Reset() {
	*x = MangaDownloadResponse{}
	mi := &file_manga_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaDownloadResponse) ProtoMessage() {}

func (x *MangaDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaDownloadResponse.ProtoReflect.Descriptor instead.
func (*MangaDownloadResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{18}
}

func (x *MangaDownloadResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MangaDownloadResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MangaDownloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MangaDownloadResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_manga_proto protoreflect.FileDescriptor

const file_manga_proto_rawDesc = "" +
	"\n" +
	"\vmanga.proto\x1a\vtypes.proto\"\x99\x02\n" +
	"\x10MangaListRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x10\n" +
	"\x03Tag\x18\x02 \x01(\tR\x03Tag\x12/\n" +
	"\x06Filter\x18\x03 \x01(\x0e2\x17.mangaweb4.types.FilterR\x06Filter\x12\x12\n" +
	"\x04Page\x18\x04 \x01(\x05R\x04Page\x12 \n" +
	"\vItemPerPage\x18\x05 \x01(\x05R\vItemPerPage\x12\x16\n" +
	"\x06Search\x18\x06 \x01(\tR\x06Search\x12.\n" +
	"\x04Sort\x18\a \x01(\x0e2\x1a.mangaweb4.types.SortFieldR\x04Sort\x120\n" +
	"\x05Order\x18\b \x01(\x0e2\x1a.mangaweb4.types.SortOrderR\x05Order\"\x81\x01\n" +
	"\x11MangaListResponse\x12 \n" +
	"\vTagFavorite\x18\x01 \x01(\bR\vTagFavorite\x12\x1c\n" +
	"\tTotalPage\x18\x02 \x01(\x05R\tTotalPage\x12,\n" +
	"\x05Items\x18\x03 \x03(\v2\x16.MangaListResponseItemR\x05Items\"\xfd\x01\n" +
	"\x15MangaListResponseItem\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"IsFavorite\x18\x03 \x01(\bR\n" +
	"IsFavorite\x12\x16\n" +
	"\x06IsRead\x18\x04 \x01(\bR\x06IsRead\x12\x1c\n" +
	"\tPageCount\x18\x05 \x01(\x05R\tPageCount\x12&\n" +
	"\x0eHasFavoriteTag\x18\x06 \x01(\bR\x0eHasFavoriteTag\x12 \n" +
	"\vCurrentPage\x18\a \x01(\x05R\vCurrentPage\x12 \n" +
	"\vMaxProgress\x18\b \x01(\x05R\vMaxProgress\"+\n" +
	"\x15MangaThumbnailRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"N\n" +
	"\x16MangaThumbnailResponse\x12 \n" +
	"\vContentType\x18\x01 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"<\n" +
	"\x12MangaDetailRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"\xb6\x01\n" +
	"\x13MangaDetailResponse\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFavorite\x18\x02 \x01(\bR\bFavorite\x12\x1c\n" +
	"\tPageCount\x18\x03 \x01(\x05R\tPageCount\x12 \n" +
	"\vCurrentPage\x18\x04 \x01(\x05R\vCurrentPage\x12/\n" +
	"\x04Tags\x18\x05 \x03(\v2\x1b.MangaDetailResponseTagItemR\x04Tags\"|\n" +
	"\x1aMangaDetailResponseTagItem\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"IsFavorite\x18\x03 \x01(\bR\n" +
	"IsFavorite\x12\x1a\n" +
	"\bIsHidden\x18\x04 \x01(\bR\bIsHidden\"]\n" +
	"\x17MangaSetFavoriteRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFavorite\x18\x03 \x01(\bR\bFavorite\"J\n" +
	"\x18MangaSetFavoriteResponse\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFavorite\x18\x02 \x01(\bR\bFavorite\"\x8d\x01\n" +
	"\x17MangaUpdateCoverRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Index\x18\x02 \x01(\x05R\x05Index\x12\f\n" +
	"\x01X\x18\x03 \x01(\x05R\x01X\x12\f\n" +
	"\x01Y\x18\x04 \x01(\x05R\x01Y\x12\x14\n" +
	"\x05Width\x18\x05 \x01(\x05R\x05Width\x12\x16\n" +
	"\x06Height\x18\x06 \x01(\x05R\x06Height\"4\n" +
	"\x18MangaUpdateCoverResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"\x83\x01\n" +
	"\x15MangaPageImageRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Index\x18\x03 \x01(\x05R\x05Index\x12\x14\n" +
	"\x05Width\x18\x04 \x01(\x05R\x05Width\x12\x16\n" +
	"\x06Height\x18\x05 \x01(\x05R\x06Height\"N\n" +
	"\x16MangaPageImageResponse\x12 \n" +
	"\vContentType\x18\x01 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"\x84\x01\n" +
	"\x1cMangaPageImageStreamResponse\x12\x1a\n" +
	"\bFilename\x18\x01 \x01(\tR\bFilename\x12 \n" +
	"\vContentType\x18\x02 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x12\n" +
	"\x04Size\x18\x04 \x01(\x05R\x04Size\"(\n" +
	"\x12MangaRepairRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"G\n" +
	"\x13MangaRepairResponse\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1c\n" +
	"\tIsSuccess\x18\x02 \x01(\bR\tIsSuccess\"*\n" +
	"\x14MangaDownloadRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"}\n" +
	"\x15MangaDownloadResponse\x12\x1a\n" +
	"\bFilename\x18\x01 \x01(\tR\bFilename\x12 \n" +
	"\vContentType\x18\x02 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x12\n" +
	"\x04Size\x18\x04 \x01(\x05R\x04Size2\xc2\x04\n" +
	"\x05Manga\x12/\n" +
	"\x04List\x12\x11.MangaListRequest\x1a\x12.MangaListResponse\"\x00\x125\n" +
	"\x06Detail\x12\x13.MangaDetailRequest\x1a\x14.MangaDetailResponse\"\x00\x12>\n" +
	"\tThumbnail\x12\x16.MangaThumbnailRequest\x1a\x17.MangaThumbnailResponse\"\x00\x12D\n" +
	"\vSetFavorite\x12\x18.MangaSetFavoriteRequest\x1a\x19.MangaSetFavoriteResponse\"\x00\x12D\n" +
	"\vUpdateCover\x12\x18.MangaUpdateCoverRequest\x1a\x19.MangaUpdateCoverResponse\"\x00\x12A\n" +
	"\tPageImage\x12\x16.MangaPageImageRequest\x1a\x17.MangaPageImageResponse\"\x03\x88\x02\x01\x12L\n" +
	"\x0fPageImageStream\x12\x16.MangaPageImageRequest\x1a\x1d.MangaPageImageStreamResponse\"\x000\x01\x125\n" +
	"\x06Repair\x12\x13.MangaRepairRequest\x1a\x14.MangaRepairResponse\"\x00\x12=\n" +
	"\bDownload\x12\x15.MangaDownloadRequest\x1a\x16.MangaDownloadResponse\"\x000\x01B-Z+github.com/mangaweb4/mangaweb4-backend/grpcb\x06proto3"

var (
	file_manga_proto_rawDescOnce sync.Once
	file_manga_proto_rawDescData []byte
)

func file_manga_proto_rawDescGZIP() []byte {
	file_manga_proto_rawDescOnce.Do(func() {
		file_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manga_proto_rawDesc), len(file_manga_proto_rawDesc)))
	})
	return file_manga_proto_rawDescData
}

var file_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_manga_proto_goTypes = []any{
	(*MangaListRequest)(nil),             // 0: MangaListRequest
	(*MangaListResponse)(nil),            // 1: MangaListResponse
	(*MangaListResponseItem)(nil),        // 2: MangaListResponseItem
	(*MangaThumbnailRequest)(nil),        // 3: MangaThumbnailRequest
	(*MangaThumbnailResponse)(nil),       // 4: MangaThumbnailResponse
	(*MangaDetailRequest)(nil),           // 5: MangaDetailRequest
	(*MangaDetailResponse)(nil),          // 6: MangaDetailResponse
	(*MangaDetailResponseTagItem)(nil),   // 7: MangaDetailResponseTagItem
	(*MangaSetFavoriteRequest)(nil),      // 8: MangaSetFavoriteRequest
	(*MangaSetFavoriteResponse)(nil),     // 9: MangaSetFavoriteResponse
	(*MangaUpdateCoverRequest)(nil),      // 10: MangaUpdateCoverRequest
	(*MangaUpdateCoverResponse)(nil),     // 11: MangaUpdateCoverResponse
	(*MangaPageImageRequest)(nil),        // 12: MangaPageImageRequest
	(*MangaPageImageResponse)(nil),       // 13: MangaPageImageResponse
	(*MangaPageImageStreamResponse)(nil), // 14: MangaPageImageStreamResponse
	(*MangaRepairRequest)(nil),           // 15: MangaRepairRequest
	(*MangaRepairResponse)(nil),          // 16: MangaRepairResponse
	(*MangaDownloadRequest)(nil),         // 17: MangaDownloadRequest
	(*MangaDownloadResponse)(nil),        // 18: MangaDownloadResponse
	(Filter)(0),                          // 19: mangaweb4.types.Filter
	(SortField)(0),                       // 20: mangaweb4.types.SortField
	(SortOrder)(0),                       // 21: mangaweb4.types.SortOrder
}
var file_manga_proto_depIdxs = []int32{
	19, // 0: MangaListRequest.Filter:type_name -> mangaweb4.types.Filter
	20, // 1: MangaListRequest.Sort:type_name -> mangaweb4.types.SortField
	21, // 2: MangaListRequest.Order:type_name -> mangaweb4.types.SortOrder
	2,  // 3: MangaListResponse.Items:type_name -> MangaListResponseItem
	7,  // 4: MangaDetailResponse.Tags:type_name -> MangaDetailResponseTagItem
	0,  // 5: Manga.List:input_type -> MangaListRequest
	5,  // 6: Manga.Detail:input_type -> MangaDetailRequest
	3,  // 7: Manga.Thumbnail:input_type -> MangaThumbnailRequest
	8,  // 8: Manga.SetFavorite:input_type -> MangaSetFavoriteRequest
	10, // 9: Manga.UpdateCover:input_type -> MangaUpdateCoverRequest
	12, // 10: Manga.PageImage:input_type -> MangaPageImageRequest
	12, // 11: Manga.PageImageStream:input_type -> MangaPageImageRequest
	15, // 12: Manga.Repair:input_type -> MangaRepairRequest
	17, // 13: Manga.Download:input_type -> MangaDownloadRequest
	1,  // 14: Manga.List:output_type -> MangaListResponse
	6,  // 15: Manga.Detail:output_type -> MangaDetailResponse
	4,  // 16: Manga.Thumbnail:output_type -> MangaThumbnailResponse
	9,  // 17: Manga.SetFavorite:output_type -> MangaSetFavoriteResponse
	11, // 18: Manga.UpdateCover:output_type -> MangaUpdateCoverResponse
	13, // 19: Manga.PageImage:output_type -> MangaPageImageResponse
	14, // 20: Manga.PageImageStream:output_type -> MangaPageImageStreamResponse
	16, // 21: Manga.Repair:output_type -> MangaRepairResponse
	18, // 22: Manga.Download:output_type -> MangaDownloadResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_manga_proto_init() }
func file_manga_proto_init() {
	if File_manga_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manga_proto_rawDesc), len(file_manga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manga_proto_goTypes,
		DependencyIndexes: file_manga_proto_depIdxs,
		MessageInfos:      file_manga_proto_msgTypes,
	}.Build()
	File_manga_proto = out.File
	file_manga_proto_goTypes = nil
	file_manga_proto_depIdxs = nil
}
