// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: manga.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Manga_List_FullMethodName        = "/Manga/List"
	Manga_Detail_FullMethodName      = "/Manga/Detail"
	Manga_Thumbnail_FullMethodName   = "/Manga/Thumbnail"
	Manga_SetFavorite_FullMethodName = "/Manga/SetFavorite"
	Manga_UpdateCover_FullMethodName = "/Manga/UpdateCover"
	Manga_PageImage_FullMethodName   = "/Manga/PageImage"
)

// MangaClient is the client API for Manga service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MangaClient interface {
	List(ctx context.Context, in *MangaListRequest, opts ...grpc.CallOption) (*MangaListResponse, error)
	Detail(ctx context.Context, in *MangaDetailRequest, opts ...grpc.CallOption) (*MangaDetailResponse, error)
	Thumbnail(ctx context.Context, in *MangaThumbnailRequest, opts ...grpc.CallOption) (*MangaThumbnailResponse, error)
	SetFavorite(ctx context.Context, in *MangaSetFavoriteRequest, opts ...grpc.CallOption) (*MangaSetFavoriteResponse, error)
	UpdateCover(ctx context.Context, in *MangaUpdateCoverRequest, opts ...grpc.CallOption) (*MangaUpdateCoverResponse, error)
	PageImage(ctx context.Context, in *MangaPageImageRequest, opts ...grpc.CallOption) (*MangaPageImageResponse, error)
}

type mangaClient struct {
	cc grpc.ClientConnInterface
}

func NewMangaClient(cc grpc.ClientConnInterface) MangaClient {
	return &mangaClient{cc}
}

func (c *mangaClient) List(ctx context.Context, in *MangaListRequest, opts ...grpc.CallOption) (*MangaListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaListResponse)
	err := c.cc.Invoke(ctx, Manga_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaClient) Detail(ctx context.Context, in *MangaDetailRequest, opts ...grpc.CallOption) (*MangaDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaDetailResponse)
	err := c.cc.Invoke(ctx, Manga_Detail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaClient) Thumbnail(ctx context.Context, in *MangaThumbnailRequest, opts ...grpc.CallOption) (*MangaThumbnailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaThumbnailResponse)
	err := c.cc.Invoke(ctx, Manga_Thumbnail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaClient) SetFavorite(ctx context.Context, in *MangaSetFavoriteRequest, opts ...grpc.CallOption) (*MangaSetFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaSetFavoriteResponse)
	err := c.cc.Invoke(ctx, Manga_SetFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaClient) UpdateCover(ctx context.Context, in *MangaUpdateCoverRequest, opts ...grpc.CallOption) (*MangaUpdateCoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaUpdateCoverResponse)
	err := c.cc.Invoke(ctx, Manga_UpdateCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaClient) PageImage(ctx context.Context, in *MangaPageImageRequest, opts ...grpc.CallOption) (*MangaPageImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaPageImageResponse)
	err := c.cc.Invoke(ctx, Manga_PageImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MangaServer is the server API for Manga service.
// All implementations must embed UnimplementedMangaServer
// for forward compatibility.
type MangaServer interface {
	List(context.Context, *MangaListRequest) (*MangaListResponse, error)
	Detail(context.Context, *MangaDetailRequest) (*MangaDetailResponse, error)
	Thumbnail(context.Context, *MangaThumbnailRequest) (*MangaThumbnailResponse, error)
	SetFavorite(context.Context, *MangaSetFavoriteRequest) (*MangaSetFavoriteResponse, error)
	UpdateCover(context.Context, *MangaUpdateCoverRequest) (*MangaUpdateCoverResponse, error)
	PageImage(context.Context, *MangaPageImageRequest) (*MangaPageImageResponse, error)
	mustEmbedUnimplementedMangaServer()
}

// UnimplementedMangaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMangaServer struct{}

func (UnimplementedMangaServer) List(context.Context, *MangaListRequest) (*MangaListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedMangaServer) Detail(context.Context, *MangaDetailRequest) (*MangaDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detail not implemented")
}
func (UnimplementedMangaServer) Thumbnail(context.Context, *MangaThumbnailRequest) (*MangaThumbnailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Thumbnail not implemented")
}
func (UnimplementedMangaServer) SetFavorite(context.Context, *MangaSetFavoriteRequest) (*MangaSetFavoriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFavorite not implemented")
}
func (UnimplementedMangaServer) UpdateCover(context.Context, *MangaUpdateCoverRequest) (*MangaUpdateCoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCover not implemented")
}
func (UnimplementedMangaServer) PageImage(context.Context, *MangaPageImageRequest) (*MangaPageImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageImage not implemented")
}
func (UnimplementedMangaServer) mustEmbedUnimplementedMangaServer() {}
func (UnimplementedMangaServer) testEmbeddedByValue()               {}

// UnsafeMangaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MangaServer will
// result in compilation errors.
type UnsafeMangaServer interface {
	mustEmbedUnimplementedMangaServer()
}

func RegisterMangaServer(s grpc.ServiceRegistrar, srv MangaServer) {
	// If the following call pancis, it indicates UnimplementedMangaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Manga_ServiceDesc, srv)
}

func _Manga_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manga_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServer).List(ctx, req.(*MangaListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manga_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manga_Detail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServer).Detail(ctx, req.(*MangaDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manga_Thumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaThumbnailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServer).Thumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manga_Thumbnail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServer).Thumbnail(ctx, req.(*MangaThumbnailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manga_SetFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaSetFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServer).SetFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manga_SetFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServer).SetFavorite(ctx, req.(*MangaSetFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manga_UpdateCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaUpdateCoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServer).UpdateCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manga_UpdateCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServer).UpdateCover(ctx, req.(*MangaUpdateCoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manga_PageImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaPageImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServer).PageImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manga_PageImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServer).PageImage(ctx, req.(*MangaPageImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Manga_ServiceDesc is the grpc.ServiceDesc for Manga service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Manga_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Manga",
	HandlerType: (*MangaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Manga_List_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _Manga_Detail_Handler,
		},
		{
			MethodName: "Thumbnail",
			Handler:    _Manga_Thumbnail_Handler,
		},
		{
			MethodName: "SetFavorite",
			Handler:    _Manga_SetFavorite_Handler,
		},
		{
			MethodName: "UpdateCover",
			Handler:    _Manga_UpdateCover_Handler,
		},
		{
			MethodName: "PageImage",
			Handler:    _Manga_PageImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manga.proto",
}
