// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: tag.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Filter        Filter                 `protobuf:"varint,3,opt,name=Filter,proto3,enum=mangaweb4.types.Filter" json:"Filter,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty"`
	ItemPerPage   int32                  `protobuf:"varint,5,opt,name=ItemPerPage,proto3" json:"ItemPerPage,omitempty"`
	Search        string                 `protobuf:"bytes,6,opt,name=Search,proto3" json:"Search,omitempty"`
	Sort          SortField              `protobuf:"varint,7,opt,name=Sort,proto3,enum=mangaweb4.types.SortField" json:"Sort,omitempty"`
	Order         SortOrder              `protobuf:"varint,8,opt,name=Order,proto3,enum=mangaweb4.types.SortOrder" json:"Order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListRequest) Reset() {
	*x = TagListRequest{}
	mi := &file_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListRequest) ProtoMessage() {}

func (x *TagListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListRequest.ProtoReflect.Descriptor instead.
func (*TagListRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{0}
}

func (x *TagListRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TagListRequest) GetFilter() Filter {
	if x != nil {
		return x.Filter
	}
	return Filter_FILTER_UNKNOWN
}

func (x *TagListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TagListRequest) GetItemPerPage() int32 {
	if x != nil {
		return x.ItemPerPage
	}
	return 0
}

func (x *TagListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *TagListRequest) GetSort() SortField {
	if x != nil {
		return x.Sort
	}
	return SortField_SORT_FIELD_NAME
}

func (x *TagListRequest) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_SORT_ORDER_ASCENDING
}

type TagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagFavorite   bool                   `protobuf:"varint,1,opt,name=TagFavorite,proto3" json:"TagFavorite,omitempty"`
	TotalPage     int32                  `protobuf:"varint,2,opt,name=TotalPage,proto3" json:"TotalPage,omitempty"`
	Items         []*TagListResponseItem `protobuf:"bytes,3,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListResponse) Reset() {
	*x = TagListResponse{}
	mi := &file_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponse) ProtoMessage() {}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponse.ProtoReflect.Descriptor instead.
func (*TagListResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{1}
}

func (x *TagListResponse) GetTagFavorite() bool {
	if x != nil {
		return x.TagFavorite
	}
	return false
}

func (x *TagListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *TagListResponse) GetItems() []*TagListResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TagListResponseItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IsFavorite     bool                   `protobuf:"varint,3,opt,name=IsFavorite,proto3" json:"IsFavorite,omitempty"`
	IsRead         bool                   `protobuf:"varint,4,opt,name=IsRead,proto3" json:"IsRead,omitempty"`
	PageCount      int32                  `protobuf:"varint,5,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	HasFavoriteTag bool                   `protobuf:"varint,6,opt,name=HasFavoriteTag,proto3" json:"HasFavoriteTag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TagListResponseItem) Reset() {
	*x = TagListResponseItem{}
	mi := &file_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponseItem) ProtoMessage() {}

func (x *TagListResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponseItem.ProtoReflect.Descriptor instead.
func (*TagListResponseItem) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{2}
}

func (x *TagListResponseItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagListResponseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagListResponseItem) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *TagListResponseItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *TagListResponseItem) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *TagListResponseItem) GetHasFavoriteTag() bool {
	if x != nil {
		return x.HasFavoriteTag
	}
	return false
}

type TagThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagThumbnailRequest) Reset() {
	*x = TagThumbnailRequest{}
	mi := &file_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagThumbnailRequest) ProtoMessage() {}

func (x *TagThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagThumbnailRequest.ProtoReflect.Descriptor instead.
func (*TagThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{3}
}

func (x *TagThumbnailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TagThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagThumbnailResponse) Reset() {
	*x = TagThumbnailResponse{}
	mi := &file_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagThumbnailResponse) ProtoMessage() {}

func (x *TagThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagThumbnailResponse.ProtoReflect.Descriptor instead.
func (*TagThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{4}
}

func (x *TagThumbnailResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TagThumbnailResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TagSetFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Favorite      bool                   `protobuf:"varint,3,opt,name=Favorite,proto3" json:"Favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagSetFavoriteRequest) Reset() {
	*x = TagSetFavoriteRequest{}
	mi := &file_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSetFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSetFavoriteRequest) ProtoMessage() {}

func (x *TagSetFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSetFavoriteRequest.ProtoReflect.Descriptor instead.
func (*TagSetFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{5}
}

func (x *TagSetFavoriteRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TagSetFavoriteRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagSetFavoriteRequest) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type TagSetFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Favorite      bool                   `protobuf:"varint,2,opt,name=Favorite,proto3" json:"Favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagSetFavoriteResponse) Reset() {
	*x = TagSetFavoriteResponse{}
	mi := &file_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSetFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSetFavoriteResponse) ProtoMessage() {}

func (x *TagSetFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSetFavoriteResponse.ProtoReflect.Descriptor instead.
func (*TagSetFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{6}
}

func (x *TagSetFavoriteResponse) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagSetFavoriteResponse) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

var File_tag_proto protoreflect.FileDescriptor

const file_tag_proto_rawDesc = "" +
	"\n" +
	"\ttag.proto\x1a\vtypes.proto\"\x8b\x02\n" +
	"\x0eTagListRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12/\n" +
	"\x06Filter\x18\x03 \x01(\x0e2\x17.mangaweb4.types.FilterR\x06Filter\x12\x12\n" +
	"\x04Page\x18\x04 \x01(\x05R\x04Page\x12 \n" +
	"\vItemPerPage\x18\x05 \x01(\x05R\vItemPerPage\x12\x16\n" +
	"\x06Search\x18\x06 \x01(\tR\x06Search\x12.\n" +
	"\x04Sort\x18\a \x01(\x0e2\x1a.mangaweb4.types.SortFieldR\x04Sort\x120\n" +
	"\x05Order\x18\b \x01(\x0e2\x1a.mangaweb4.types.SortOrderR\x05OrderJ\x04\b\x02\x10\x03\"}\n" +
	"\x0fTagListResponse\x12 \n" +
	"\vTagFavorite\x18\x01 \x01(\bR\vTagFavorite\x12\x1c\n" +
	"\tTotalPage\x18\x02 \x01(\x05R\tTotalPage\x12*\n" +
	"\x05Items\x18\x03 \x03(\v2\x14.TagListResponseItemR\x05Items\"\xb7\x01\n" +
	"\x13TagListResponseItem\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"IsFavorite\x18\x03 \x01(\bR\n" +
	"IsFavorite\x12\x16\n" +
	"\x06IsRead\x18\x04 \x01(\bR\x06IsRead\x12\x1c\n" +
	"\tPageCount\x18\x05 \x01(\x05R\tPageCount\x12&\n" +
	"\x0eHasFavoriteTag\x18\x06 \x01(\bR\x0eHasFavoriteTag\")\n" +
	"\x13TagThumbnailRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"L\n" +
	"\x14TagThumbnailResponse\x12 \n" +
	"\vContentType\x18\x01 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"Y\n" +
	"\x15TagSetFavoriteRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x10\n" +
	"\x03Tag\x18\x02 \x01(\tR\x03Tag\x12\x1a\n" +
	"\bFavorite\x18\x03 \x01(\bR\bFavorite\"F\n" +
	"\x16TagSetFavoriteResponse\x12\x10\n" +
	"\x03Tag\x18\x01 \x01(\tR\x03Tag\x12\x1a\n" +
	"\bFavorite\x18\x02 \x01(\bR\bFavorite2\xb0\x01\n" +
	"\x03Tag\x12+\n" +
	"\x04List\x12\x0f.TagListRequest\x1a\x10.TagListResponse\"\x00\x12:\n" +
	"\tThumbnail\x12\x14.TagThumbnailRequest\x1a\x15.TagThumbnailResponse\"\x00\x12@\n" +
	"\vSetFavorite\x12\x16.TagSetFavoriteRequest\x1a\x17.TagSetFavoriteResponse\"\x00B-Z+github.com/mangaweb4/mangaweb4-backend/grpcb\x06proto3"

var (
	file_tag_proto_rawDescOnce sync.Once
	file_tag_proto_rawDescData []byte
)

func file_tag_proto_rawDescGZIP() []byte {
	file_tag_proto_rawDescOnce.Do(func() {
		file_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)))
	})
	return file_tag_proto_rawDescData
}

var file_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tag_proto_goTypes = []any{
	(*TagListRequest)(nil),         // 0: TagListRequest
	(*TagListResponse)(nil),        // 1: TagListResponse
	(*TagListResponseItem)(nil),    // 2: TagListResponseItem
	(*TagThumbnailRequest)(nil),    // 3: TagThumbnailRequest
	(*TagThumbnailResponse)(nil),   // 4: TagThumbnailResponse
	(*TagSetFavoriteRequest)(nil),  // 5: TagSetFavoriteRequest
	(*TagSetFavoriteResponse)(nil), // 6: TagSetFavoriteResponse
	(Filter)(0),                    // 7: mangaweb4.types.Filter
	(SortField)(0),                 // 8: mangaweb4.types.SortField
	(SortOrder)(0),                 // 9: mangaweb4.types.SortOrder
}
var file_tag_proto_depIdxs = []int32{
	7, // 0: TagListRequest.Filter:type_name -> mangaweb4.types.Filter
	8, // 1: TagListRequest.Sort:type_name -> mangaweb4.types.SortField
	9, // 2: TagListRequest.Order:type_name -> mangaweb4.types.SortOrder
	2, // 3: TagListResponse.Items:type_name -> TagListResponseItem
	0, // 4: Tag.List:input_type -> TagListRequest
	3, // 5: Tag.Thumbnail:input_type -> TagThumbnailRequest
	5, // 6: Tag.SetFavorite:input_type -> TagSetFavoriteRequest
	1, // 7: Tag.List:output_type -> TagListResponse
	4, // 8: Tag.Thumbnail:output_type -> TagThumbnailResponse
	6, // 9: Tag.SetFavorite:output_type -> TagSetFavoriteResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tag_proto_init() }
func file_tag_proto_init() {
	if File_tag_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_proto_goTypes,
		DependencyIndexes: file_tag_proto_depIdxs,
		MessageInfos:      file_tag_proto_msgTypes,
	}.Build()
	File_tag_proto = out.File
	file_tag_proto_goTypes = nil
	file_tag_proto_depIdxs = nil
}
