// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: view.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewDetailRequest) Reset() {
	*x = ViewDetailRequest{}
	mi := &file_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewDetailRequest) ProtoMessage() {}

func (x *ViewDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewDetailRequest.ProtoReflect.Descriptor instead.
func (*ViewDetailRequest) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{0}
}

func (x *ViewDetailRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ViewDetailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ViewDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Favorite      bool                   `protobuf:"varint,2,opt,name=Favorite,proto3" json:"Favorite,omitempty"`
	PageCount     int32                  `protobuf:"varint,3,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,4,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewDetailResponse) Reset() {
	*x = ViewDetailResponse{}
	mi := &file_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewDetailResponse) ProtoMessage() {}

func (x *ViewDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewDetailResponse.ProtoReflect.Descriptor instead.
func (*ViewDetailResponse) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{1}
}

func (x *ViewDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ViewDetailResponse) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

func (x *ViewDetailResponse) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *ViewDetailResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ViewDetailResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ViewImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewImageRequest) Reset() {
	*x = ViewImageRequest{}
	mi := &file_view_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewImageRequest) ProtoMessage() {}

func (x *ViewImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewImageRequest.ProtoReflect.Descriptor instead.
func (*ViewImageRequest) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{2}
}

func (x *ViewImageRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ViewImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ViewImageRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ViewImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewImageResponse) Reset() {
	*x = ViewImageResponse{}
	mi := &file_view_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewImageResponse) ProtoMessage() {}

func (x *ViewImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewImageResponse.ProtoReflect.Descriptor instead.
func (*ViewImageResponse) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{3}
}

func (x *ViewImageResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ViewImageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_view_proto protoreflect.FileDescriptor

const file_view_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"view.proto\";\n" +
	"\x11ViewDetailRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"\x98\x01\n" +
	"\x12ViewDetailResponse\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFavorite\x18\x02 \x01(\bR\bFavorite\x12\x1c\n" +
	"\tPageCount\x18\x03 \x01(\x05R\tPageCount\x12 \n" +
	"\vCurrentPage\x18\x04 \x01(\x05R\vCurrentPage\x12\x12\n" +
	"\x04Tags\x18\x05 \x03(\tR\x04Tags\"P\n" +
	"\x10ViewImageRequest\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Index\x18\x03 \x01(\x05R\x05Index\"I\n" +
	"\x11ViewImageResponse\x12 \n" +
	"\vContentType\x18\x01 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data2m\n" +
	"\x04View\x123\n" +
	"\x06Detail\x12\x12.ViewDetailRequest\x1a\x13.ViewDetailResponse\"\x00\x120\n" +
	"\x05Image\x12\x11.ViewImageRequest\x1a\x12.ViewImageResponse\"\x00B-Z+github.com/mangaweb4/mangaweb4-backend/grpcb\x06proto3"

var (
	file_view_proto_rawDescOnce sync.Once
	file_view_proto_rawDescData []byte
)

func file_view_proto_rawDescGZIP() []byte {
	file_view_proto_rawDescOnce.Do(func() {
		file_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_view_proto_rawDesc), len(file_view_proto_rawDesc)))
	})
	return file_view_proto_rawDescData
}

var file_view_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_view_proto_goTypes = []any{
	(*ViewDetailRequest)(nil),  // 0: ViewDetailRequest
	(*ViewDetailResponse)(nil), // 1: ViewDetailResponse
	(*ViewImageRequest)(nil),   // 2: ViewImageRequest
	(*ViewImageResponse)(nil),  // 3: ViewImageResponse
}
var file_view_proto_depIdxs = []int32{
	0, // 0: View.Detail:input_type -> ViewDetailRequest
	2, // 1: View.Image:input_type -> ViewImageRequest
	1, // 2: View.Detail:output_type -> ViewDetailResponse
	3, // 3: View.Image:output_type -> ViewImageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_view_proto_init() }
func file_view_proto_init() {
	if File_view_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_view_proto_rawDesc), len(file_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_view_proto_goTypes,
		DependencyIndexes: file_view_proto_depIdxs,
		MessageInfos:      file_view_proto_msgTypes,
	}.Build()
	File_view_proto = out.File
	file_view_proto_goTypes = nil
	file_view_proto_depIdxs = nil
}
