// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mangaweb4/mangaweb4-backend/ent/serie"
)

// Serie is the model entity for the Serie schema.
type Serie struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Hidden holds the value of the "hidden" field.
	Hidden bool `json:"hidden,omitempty"`
	// LastUpdate holds the value of the "last_update" field.
	LastUpdate time.Time `json:"last_update,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SerieQuery when eager-loading is set.
	Edges        SerieEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SerieEdges holds the relations/edges for other nodes in the graph.
type SerieEdges struct {
	// Items holds the value of the items edge.
	Items []*Meta `json:"items,omitempty"`
	// FavoriteOfUser holds the value of the favorite_of_user edge.
	FavoriteOfUser []*User `json:"favorite_of_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e SerieEdges) ItemsOrErr() ([]*Meta, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// FavoriteOfUserOrErr returns the FavoriteOfUser value or an error if the edge
// was not loaded in eager-loading.
func (e SerieEdges) FavoriteOfUserOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.FavoriteOfUser, nil
	}
	return nil, &NotLoadedError{edge: "favorite_of_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Serie) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serie.FieldHidden:
			values[i] = new(sql.NullBool)
		case serie.FieldID:
			values[i] = new(sql.NullInt64)
		case serie.FieldName:
			values[i] = new(sql.NullString)
		case serie.FieldLastUpdate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Serie fields.
func (s *Serie) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serie.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case serie.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case serie.FieldHidden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field hidden", values[i])
			} else if value.Valid {
				s.Hidden = value.Bool
			}
		case serie.FieldLastUpdate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_update", values[i])
			} else if value.Valid {
				s.LastUpdate = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Serie.
// This includes values selected through modifiers, order, etc.
func (s *Serie) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the Serie entity.
func (s *Serie) QueryItems() *MetaQuery {
	return NewSerieClient(s.config).QueryItems(s)
}

// QueryFavoriteOfUser queries the "favorite_of_user" edge of the Serie entity.
func (s *Serie) QueryFavoriteOfUser() *UserQuery {
	return NewSerieClient(s.config).QueryFavoriteOfUser(s)
}

// Update returns a builder for updating this Serie.
// Note that you need to call Serie.Unwrap() before calling this method if this Serie
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Serie) Update() *SerieUpdateOne {
	return NewSerieClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Serie entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Serie) Unwrap() *Serie {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Serie is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Serie) String() string {
	var builder strings.Builder
	builder.WriteString("Serie(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("hidden=")
	builder.WriteString(fmt.Sprintf("%v", s.Hidden))
	builder.WriteString(", ")
	builder.WriteString("last_update=")
	builder.WriteString(s.LastUpdate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Series is a parsable slice of Serie.
type Series []*Serie
