// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mangaweb4/mangaweb4-backend/ent/meta"
	"github.com/mangaweb4/mangaweb4-backend/ent/predicate"
	"github.com/mangaweb4/mangaweb4-backend/ent/serie"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// SerieUpdate is the builder for updating Serie entities.
type SerieUpdate struct {
	config
	hooks    []Hook
	mutation *SerieMutation
}

// Where appends a list predicates to the SerieUpdate builder.
func (su *SerieUpdate) Where(ps ...predicate.Serie) *SerieUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SerieUpdate) SetName(s string) *SerieUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SerieUpdate) SetNillableName(s *string) *SerieUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetHidden sets the "hidden" field.
func (su *SerieUpdate) SetHidden(b bool) *SerieUpdate {
	su.mutation.SetHidden(b)
	return su
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (su *SerieUpdate) SetNillableHidden(b *bool) *SerieUpdate {
	if b != nil {
		su.SetHidden(*b)
	}
	return su
}

// SetLastUpdate sets the "last_update" field.
func (su *SerieUpdate) SetLastUpdate(t time.Time) *SerieUpdate {
	su.mutation.SetLastUpdate(t)
	return su
}

// SetNillableLastUpdate sets the "last_update" field if the given value is not nil.
func (su *SerieUpdate) SetNillableLastUpdate(t *time.Time) *SerieUpdate {
	if t != nil {
		su.SetLastUpdate(*t)
	}
	return su
}

// AddItemIDs adds the "items" edge to the Meta entity by IDs.
func (su *SerieUpdate) AddItemIDs(ids ...int) *SerieUpdate {
	su.mutation.AddItemIDs(ids...)
	return su
}

// AddItems adds the "items" edges to the Meta entity.
func (su *SerieUpdate) AddItems(m ...*Meta) *SerieUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return su.AddItemIDs(ids...)
}

// AddFavoriteOfUserIDs adds the "favorite_of_user" edge to the User entity by IDs.
func (su *SerieUpdate) AddFavoriteOfUserIDs(ids ...int) *SerieUpdate {
	su.mutation.AddFavoriteOfUserIDs(ids...)
	return su
}

// AddFavoriteOfUser adds the "favorite_of_user" edges to the User entity.
func (su *SerieUpdate) AddFavoriteOfUser(u ...*User) *SerieUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return su.AddFavoriteOfUserIDs(ids...)
}

// Mutation returns the SerieMutation object of the builder.
func (su *SerieUpdate) Mutation() *SerieMutation {
	return su.mutation
}

// ClearItems clears all "items" edges to the Meta entity.
func (su *SerieUpdate) ClearItems() *SerieUpdate {
	su.mutation.ClearItems()
	return su
}

// RemoveItemIDs removes the "items" edge to Meta entities by IDs.
func (su *SerieUpdate) RemoveItemIDs(ids ...int) *SerieUpdate {
	su.mutation.RemoveItemIDs(ids...)
	return su
}

// RemoveItems removes "items" edges to Meta entities.
func (su *SerieUpdate) RemoveItems(m ...*Meta) *SerieUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return su.RemoveItemIDs(ids...)
}

// ClearFavoriteOfUser clears all "favorite_of_user" edges to the User entity.
func (su *SerieUpdate) ClearFavoriteOfUser() *SerieUpdate {
	su.mutation.ClearFavoriteOfUser()
	return su
}

// RemoveFavoriteOfUserIDs removes the "favorite_of_user" edge to User entities by IDs.
func (su *SerieUpdate) RemoveFavoriteOfUserIDs(ids ...int) *SerieUpdate {
	su.mutation.RemoveFavoriteOfUserIDs(ids...)
	return su
}

// RemoveFavoriteOfUser removes "favorite_of_user" edges to User entities.
func (su *SerieUpdate) RemoveFavoriteOfUser(u ...*User) *SerieUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return su.RemoveFavoriteOfUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SerieUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SerieUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SerieUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SerieUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SerieUpdate) check() error {
	if v, ok := su.mutation.Name(); ok {
		if err := serie.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Serie.name": %w`, err)}
		}
	}
	return nil
}

func (su *SerieUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(serie.Table, serie.Columns, sqlgraph.NewFieldSpec(serie.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(serie.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Hidden(); ok {
		_spec.SetField(serie.FieldHidden, field.TypeBool, value)
	}
	if value, ok := su.mutation.LastUpdate(); ok {
		_spec.SetField(serie.FieldLastUpdate, field.TypeTime, value)
	}
	if su.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   serie.ItemsTable,
			Columns: []string{serie.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedItemsIDs(); len(nodes) > 0 && !su.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   serie.ItemsTable,
			Columns: []string{serie.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   serie.ItemsTable,
			Columns: []string{serie.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   serie.FavoriteOfUserTable,
			Columns: serie.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedFavoriteOfUserIDs(); len(nodes) > 0 && !su.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   serie.FavoriteOfUserTable,
			Columns: serie.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.FavoriteOfUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   serie.FavoriteOfUserTable,
			Columns: serie.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SerieUpdateOne is the builder for updating a single Serie entity.
type SerieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SerieMutation
}

// SetName sets the "name" field.
func (suo *SerieUpdateOne) SetName(s string) *SerieUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SerieUpdateOne) SetNillableName(s *string) *SerieUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetHidden sets the "hidden" field.
func (suo *SerieUpdateOne) SetHidden(b bool) *SerieUpdateOne {
	suo.mutation.SetHidden(b)
	return suo
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (suo *SerieUpdateOne) SetNillableHidden(b *bool) *SerieUpdateOne {
	if b != nil {
		suo.SetHidden(*b)
	}
	return suo
}

// SetLastUpdate sets the "last_update" field.
func (suo *SerieUpdateOne) SetLastUpdate(t time.Time) *SerieUpdateOne {
	suo.mutation.SetLastUpdate(t)
	return suo
}

// SetNillableLastUpdate sets the "last_update" field if the given value is not nil.
func (suo *SerieUpdateOne) SetNillableLastUpdate(t *time.Time) *SerieUpdateOne {
	if t != nil {
		suo.SetLastUpdate(*t)
	}
	return suo
}

// AddItemIDs adds the "items" edge to the Meta entity by IDs.
func (suo *SerieUpdateOne) AddItemIDs(ids ...int) *SerieUpdateOne {
	suo.mutation.AddItemIDs(ids...)
	return suo
}

// AddItems adds the "items" edges to the Meta entity.
func (suo *SerieUpdateOne) AddItems(m ...*Meta) *SerieUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return suo.AddItemIDs(ids...)
}

// AddFavoriteOfUserIDs adds the "favorite_of_user" edge to the User entity by IDs.
func (suo *SerieUpdateOne) AddFavoriteOfUserIDs(ids ...int) *SerieUpdateOne {
	suo.mutation.AddFavoriteOfUserIDs(ids...)
	return suo
}

// AddFavoriteOfUser adds the "favorite_of_user" edges to the User entity.
func (suo *SerieUpdateOne) AddFavoriteOfUser(u ...*User) *SerieUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return suo.AddFavoriteOfUserIDs(ids...)
}

// Mutation returns the SerieMutation object of the builder.
func (suo *SerieUpdateOne) Mutation() *SerieMutation {
	return suo.mutation
}

// ClearItems clears all "items" edges to the Meta entity.
func (suo *SerieUpdateOne) ClearItems() *SerieUpdateOne {
	suo.mutation.ClearItems()
	return suo
}

// RemoveItemIDs removes the "items" edge to Meta entities by IDs.
func (suo *SerieUpdateOne) RemoveItemIDs(ids ...int) *SerieUpdateOne {
	suo.mutation.RemoveItemIDs(ids...)
	return suo
}

// RemoveItems removes "items" edges to Meta entities.
func (suo *SerieUpdateOne) RemoveItems(m ...*Meta) *SerieUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return suo.RemoveItemIDs(ids...)
}

// ClearFavoriteOfUser clears all "favorite_of_user" edges to the User entity.
func (suo *SerieUpdateOne) ClearFavoriteOfUser() *SerieUpdateOne {
	suo.mutation.ClearFavoriteOfUser()
	return suo
}

// RemoveFavoriteOfUserIDs removes the "favorite_of_user" edge to User entities by IDs.
func (suo *SerieUpdateOne) RemoveFavoriteOfUserIDs(ids ...int) *SerieUpdateOne {
	suo.mutation.RemoveFavoriteOfUserIDs(ids...)
	return suo
}

// RemoveFavoriteOfUser removes "favorite_of_user" edges to User entities.
func (suo *SerieUpdateOne) RemoveFavoriteOfUser(u ...*User) *SerieUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return suo.RemoveFavoriteOfUserIDs(ids...)
}

// Where appends a list predicates to the SerieUpdate builder.
func (suo *SerieUpdateOne) Where(ps ...predicate.Serie) *SerieUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SerieUpdateOne) Select(field string, fields ...string) *SerieUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Serie entity.
func (suo *SerieUpdateOne) Save(ctx context.Context) (*Serie, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SerieUpdateOne) SaveX(ctx context.Context) *Serie {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SerieUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SerieUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SerieUpdateOne) check() error {
	if v, ok := suo.mutation.Name(); ok {
		if err := serie.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Serie.name": %w`, err)}
		}
	}
	return nil
}

func (suo *SerieUpdateOne) sqlSave(ctx context.Context) (_node *Serie, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serie.Table, serie.Columns, sqlgraph.NewFieldSpec(serie.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Serie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serie.FieldID)
		for _, f := range fields {
			if !serie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(serie.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Hidden(); ok {
		_spec.SetField(serie.FieldHidden, field.TypeBool, value)
	}
	if value, ok := suo.mutation.LastUpdate(); ok {
		_spec.SetField(serie.FieldLastUpdate, field.TypeTime, value)
	}
	if suo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   serie.ItemsTable,
			Columns: []string{serie.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedItemsIDs(); len(nodes) > 0 && !suo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   serie.ItemsTable,
			Columns: []string{serie.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   serie.ItemsTable,
			Columns: []string{serie.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   serie.FavoriteOfUserTable,
			Columns: serie.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedFavoriteOfUserIDs(); len(nodes) > 0 && !suo.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   serie.FavoriteOfUserTable,
			Columns: serie.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.FavoriteOfUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   serie.FavoriteOfUserTable,
			Columns: serie.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Serie{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
