// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mangaweb4/mangaweb4-backend/ent/meta"
	"github.com/mangaweb4/mangaweb4-backend/ent/serie"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// SerieCreate is the builder for creating a Serie entity.
type SerieCreate struct {
	config
	mutation *SerieMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (sc *SerieCreate) SetName(s string) *SerieCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetHidden sets the "hidden" field.
func (sc *SerieCreate) SetHidden(b bool) *SerieCreate {
	sc.mutation.SetHidden(b)
	return sc
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (sc *SerieCreate) SetNillableHidden(b *bool) *SerieCreate {
	if b != nil {
		sc.SetHidden(*b)
	}
	return sc
}

// SetLastUpdate sets the "last_update" field.
func (sc *SerieCreate) SetLastUpdate(t time.Time) *SerieCreate {
	sc.mutation.SetLastUpdate(t)
	return sc
}

// SetNillableLastUpdate sets the "last_update" field if the given value is not nil.
func (sc *SerieCreate) SetNillableLastUpdate(t *time.Time) *SerieCreate {
	if t != nil {
		sc.SetLastUpdate(*t)
	}
	return sc
}

// AddItemIDs adds the "items" edge to the Meta entity by IDs.
func (sc *SerieCreate) AddItemIDs(ids ...int) *SerieCreate {
	sc.mutation.AddItemIDs(ids...)
	return sc
}

// AddItems adds the "items" edges to the Meta entity.
func (sc *SerieCreate) AddItems(m ...*Meta) *SerieCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return sc.AddItemIDs(ids...)
}

// AddFavoriteOfUserIDs adds the "favorite_of_user" edge to the User entity by IDs.
func (sc *SerieCreate) AddFavoriteOfUserIDs(ids ...int) *SerieCreate {
	sc.mutation.AddFavoriteOfUserIDs(ids...)
	return sc
}

// AddFavoriteOfUser adds the "favorite_of_user" edges to the User entity.
func (sc *SerieCreate) AddFavoriteOfUser(u ...*User) *SerieCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return sc.AddFavoriteOfUserIDs(ids...)
}

// Mutation returns the SerieMutation object of the builder.
func (sc *SerieCreate) Mutation() *SerieMutation {
	return sc.mutation
}

// Save creates the Serie in the database.
func (sc *SerieCreate) Save(ctx context.Context) (*Serie, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SerieCreate) SaveX(ctx context.Context) *Serie {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SerieCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SerieCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SerieCreate) defaults() {
	if _, ok := sc.mutation.Hidden(); !ok {
		v := serie.DefaultHidden
		sc.mutation.SetHidden(v)
	}
	if _, ok := sc.mutation.LastUpdate(); !ok {
		v := serie.DefaultLastUpdate()
		sc.mutation.SetLastUpdate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SerieCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Serie.name"`)}
	}
	if v, ok := sc.mutation.Name(); ok {
		if err := serie.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Serie.name": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Hidden(); !ok {
		return &ValidationError{Name: "hidden", err: errors.New(`ent: missing required field "Serie.hidden"`)}
	}
	if _, ok := sc.mutation.LastUpdate(); !ok {
		return &ValidationError{Name: "last_update", err: errors.New(`ent: missing required field "Serie.last_update"`)}
	}
	return nil
}

func (sc *SerieCreate) sqlSave(ctx context.Context) (*Serie, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SerieCreate) createSpec() (*Serie, *sqlgraph.CreateSpec) {
	var (
		_node = &Serie{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(serie.Table, sqlgraph.NewFieldSpec(serie.FieldID, field.TypeInt))
	)
	_spec.OnConflict = sc.conflict
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(serie.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Hidden(); ok {
		_spec.SetField(serie.FieldHidden, field.TypeBool, value)
		_node.Hidden = value
	}
	if value, ok := sc.mutation.LastUpdate(); ok {
		_spec.SetField(serie.FieldLastUpdate, field.TypeTime, value)
		_node.LastUpdate = value
	}
	if nodes := sc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   serie.ItemsTable,
			Columns: []string{serie.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.FavoriteOfUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   serie.FavoriteOfUserTable,
			Columns: serie.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Serie.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SerieUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (sc *SerieCreate) OnConflict(opts ...sql.ConflictOption) *SerieUpsertOne {
	sc.conflict = opts
	return &SerieUpsertOne{
		create: sc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Serie.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sc *SerieCreate) OnConflictColumns(columns ...string) *SerieUpsertOne {
	sc.conflict = append(sc.conflict, sql.ConflictColumns(columns...))
	return &SerieUpsertOne{
		create: sc,
	}
}

type (
	// SerieUpsertOne is the builder for "upsert"-ing
	//  one Serie node.
	SerieUpsertOne struct {
		create *SerieCreate
	}

	// SerieUpsert is the "OnConflict" setter.
	SerieUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SerieUpsert) SetName(v string) *SerieUpsert {
	u.Set(serie.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SerieUpsert) UpdateName() *SerieUpsert {
	u.SetExcluded(serie.FieldName)
	return u
}

// SetHidden sets the "hidden" field.
func (u *SerieUpsert) SetHidden(v bool) *SerieUpsert {
	u.Set(serie.FieldHidden, v)
	return u
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *SerieUpsert) UpdateHidden() *SerieUpsert {
	u.SetExcluded(serie.FieldHidden)
	return u
}

// SetLastUpdate sets the "last_update" field.
func (u *SerieUpsert) SetLastUpdate(v time.Time) *SerieUpsert {
	u.Set(serie.FieldLastUpdate, v)
	return u
}

// UpdateLastUpdate sets the "last_update" field to the value that was provided on create.
func (u *SerieUpsert) UpdateLastUpdate() *SerieUpsert {
	u.SetExcluded(serie.FieldLastUpdate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Serie.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SerieUpsertOne) UpdateNewValues() *SerieUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Serie.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SerieUpsertOne) Ignore() *SerieUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SerieUpsertOne) DoNothing() *SerieUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SerieCreate.OnConflict
// documentation for more info.
func (u *SerieUpsertOne) Update(set func(*SerieUpsert)) *SerieUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SerieUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SerieUpsertOne) SetName(v string) *SerieUpsertOne {
	return u.Update(func(s *SerieUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SerieUpsertOne) UpdateName() *SerieUpsertOne {
	return u.Update(func(s *SerieUpsert) {
		s.UpdateName()
	})
}

// SetHidden sets the "hidden" field.
func (u *SerieUpsertOne) SetHidden(v bool) *SerieUpsertOne {
	return u.Update(func(s *SerieUpsert) {
		s.SetHidden(v)
	})
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *SerieUpsertOne) UpdateHidden() *SerieUpsertOne {
	return u.Update(func(s *SerieUpsert) {
		s.UpdateHidden()
	})
}

// SetLastUpdate sets the "last_update" field.
func (u *SerieUpsertOne) SetLastUpdate(v time.Time) *SerieUpsertOne {
	return u.Update(func(s *SerieUpsert) {
		s.SetLastUpdate(v)
	})
}

// UpdateLastUpdate sets the "last_update" field to the value that was provided on create.
func (u *SerieUpsertOne) UpdateLastUpdate() *SerieUpsertOne {
	return u.Update(func(s *SerieUpsert) {
		s.UpdateLastUpdate()
	})
}

// Exec executes the query.
func (u *SerieUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SerieCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SerieUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SerieUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SerieUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SerieCreateBulk is the builder for creating many Serie entities in bulk.
type SerieCreateBulk struct {
	config
	err      error
	builders []*SerieCreate
	conflict []sql.ConflictOption
}

// Save creates the Serie entities in the database.
func (scb *SerieCreateBulk) Save(ctx context.Context) ([]*Serie, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Serie, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SerieMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = scb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SerieCreateBulk) SaveX(ctx context.Context) []*Serie {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SerieCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SerieCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Serie.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SerieUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (scb *SerieCreateBulk) OnConflict(opts ...sql.ConflictOption) *SerieUpsertBulk {
	scb.conflict = opts
	return &SerieUpsertBulk{
		create: scb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Serie.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (scb *SerieCreateBulk) OnConflictColumns(columns ...string) *SerieUpsertBulk {
	scb.conflict = append(scb.conflict, sql.ConflictColumns(columns...))
	return &SerieUpsertBulk{
		create: scb,
	}
}

// SerieUpsertBulk is the builder for "upsert"-ing
// a bulk of Serie nodes.
type SerieUpsertBulk struct {
	create *SerieCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Serie.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SerieUpsertBulk) UpdateNewValues() *SerieUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Serie.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SerieUpsertBulk) Ignore() *SerieUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SerieUpsertBulk) DoNothing() *SerieUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SerieCreateBulk.OnConflict
// documentation for more info.
func (u *SerieUpsertBulk) Update(set func(*SerieUpsert)) *SerieUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SerieUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SerieUpsertBulk) SetName(v string) *SerieUpsertBulk {
	return u.Update(func(s *SerieUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SerieUpsertBulk) UpdateName() *SerieUpsertBulk {
	return u.Update(func(s *SerieUpsert) {
		s.UpdateName()
	})
}

// SetHidden sets the "hidden" field.
func (u *SerieUpsertBulk) SetHidden(v bool) *SerieUpsertBulk {
	return u.Update(func(s *SerieUpsert) {
		s.SetHidden(v)
	})
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *SerieUpsertBulk) UpdateHidden() *SerieUpsertBulk {
	return u.Update(func(s *SerieUpsert) {
		s.UpdateHidden()
	})
}

// SetLastUpdate sets the "last_update" field.
func (u *SerieUpsertBulk) SetLastUpdate(v time.Time) *SerieUpsertBulk {
	return u.Update(func(s *SerieUpsert) {
		s.SetLastUpdate(v)
	})
}

// UpdateLastUpdate sets the "last_update" field to the value that was provided on create.
func (u *SerieUpsertBulk) UpdateLastUpdate() *SerieUpsertBulk {
	return u.Update(func(s *SerieUpsert) {
		s.UpdateLastUpdate()
	})
}

// Exec executes the query.
func (u *SerieUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SerieCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SerieCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SerieUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
