// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mangaweb4/mangaweb4-backend/ent/meta"
	"github.com/mangaweb4/mangaweb4-backend/ent/predicate"
	"github.com/mangaweb4/mangaweb4-backend/ent/serie"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// SerieQuery is the builder for querying Serie entities.
type SerieQuery struct {
	config
	ctx                *QueryContext
	order              []serie.OrderOption
	inters             []Interceptor
	predicates         []predicate.Serie
	withItems          *MetaQuery
	withFavoriteOfUser *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SerieQuery builder.
func (sq *SerieQuery) Where(ps ...predicate.Serie) *SerieQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SerieQuery) Limit(limit int) *SerieQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SerieQuery) Offset(offset int) *SerieQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SerieQuery) Unique(unique bool) *SerieQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SerieQuery) Order(o ...serie.OrderOption) *SerieQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryItems chains the current query on the "items" edge.
func (sq *SerieQuery) QueryItems() *MetaQuery {
	query := (&MetaClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(serie.Table, serie.FieldID, selector),
			sqlgraph.To(meta.Table, meta.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, serie.ItemsTable, serie.ItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFavoriteOfUser chains the current query on the "favorite_of_user" edge.
func (sq *SerieQuery) QueryFavoriteOfUser() *UserQuery {
	query := (&UserClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(serie.Table, serie.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, serie.FavoriteOfUserTable, serie.FavoriteOfUserPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Serie entity from the query.
// Returns a *NotFoundError when no Serie was found.
func (sq *SerieQuery) First(ctx context.Context) (*Serie, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{serie.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SerieQuery) FirstX(ctx context.Context) *Serie {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Serie ID from the query.
// Returns a *NotFoundError when no Serie ID was found.
func (sq *SerieQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{serie.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SerieQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Serie entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Serie entity is found.
// Returns a *NotFoundError when no Serie entities are found.
func (sq *SerieQuery) Only(ctx context.Context) (*Serie, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{serie.Label}
	default:
		return nil, &NotSingularError{serie.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SerieQuery) OnlyX(ctx context.Context) *Serie {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Serie ID in the query.
// Returns a *NotSingularError when more than one Serie ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SerieQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{serie.Label}
	default:
		err = &NotSingularError{serie.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SerieQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Series.
func (sq *SerieQuery) All(ctx context.Context) ([]*Serie, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Serie, *SerieQuery]()
	return withInterceptors[[]*Serie](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SerieQuery) AllX(ctx context.Context) []*Serie {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Serie IDs.
func (sq *SerieQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(serie.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SerieQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SerieQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SerieQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SerieQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SerieQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SerieQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SerieQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SerieQuery) Clone() *SerieQuery {
	if sq == nil {
		return nil
	}
	return &SerieQuery{
		config:             sq.config,
		ctx:                sq.ctx.Clone(),
		order:              append([]serie.OrderOption{}, sq.order...),
		inters:             append([]Interceptor{}, sq.inters...),
		predicates:         append([]predicate.Serie{}, sq.predicates...),
		withItems:          sq.withItems.Clone(),
		withFavoriteOfUser: sq.withFavoriteOfUser.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithItems tells the query-builder to eager-load the nodes that are connected to
// the "items" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SerieQuery) WithItems(opts ...func(*MetaQuery)) *SerieQuery {
	query := (&MetaClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withItems = query
	return sq
}

// WithFavoriteOfUser tells the query-builder to eager-load the nodes that are connected to
// the "favorite_of_user" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SerieQuery) WithFavoriteOfUser(opts ...func(*UserQuery)) *SerieQuery {
	query := (&UserClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withFavoriteOfUser = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Serie.Query().
//		GroupBy(serie.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SerieQuery) GroupBy(field string, fields ...string) *SerieGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SerieGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = serie.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Serie.Query().
//		Select(serie.FieldName).
//		Scan(ctx, &v)
func (sq *SerieQuery) Select(fields ...string) *SerieSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SerieSelect{SerieQuery: sq}
	sbuild.label = serie.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SerieSelect configured with the given aggregations.
func (sq *SerieQuery) Aggregate(fns ...AggregateFunc) *SerieSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SerieQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !serie.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SerieQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Serie, error) {
	var (
		nodes       = []*Serie{}
		_spec       = sq.querySpec()
		loadedTypes = [2]bool{
			sq.withItems != nil,
			sq.withFavoriteOfUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Serie).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Serie{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withItems; query != nil {
		if err := sq.loadItems(ctx, query, nodes,
			func(n *Serie) { n.Edges.Items = []*Meta{} },
			func(n *Serie, e *Meta) { n.Edges.Items = append(n.Edges.Items, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withFavoriteOfUser; query != nil {
		if err := sq.loadFavoriteOfUser(ctx, query, nodes,
			func(n *Serie) { n.Edges.FavoriteOfUser = []*User{} },
			func(n *Serie, e *User) { n.Edges.FavoriteOfUser = append(n.Edges.FavoriteOfUser, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SerieQuery) loadItems(ctx context.Context, query *MetaQuery, nodes []*Serie, init func(*Serie), assign func(*Serie, *Meta)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Serie)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Meta(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(serie.ItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.meta_serie
		if fk == nil {
			return fmt.Errorf(`foreign-key "meta_serie" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "meta_serie" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SerieQuery) loadFavoriteOfUser(ctx context.Context, query *UserQuery, nodes []*Serie, init func(*Serie), assign func(*Serie, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Serie)
	nids := make(map[int]map[*Serie]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(serie.FavoriteOfUserTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(serie.FavoriteOfUserPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(serie.FavoriteOfUserPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(serie.FavoriteOfUserPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Serie]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "favorite_of_user" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (sq *SerieQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SerieQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(serie.Table, serie.Columns, sqlgraph.NewFieldSpec(serie.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serie.FieldID)
		for i := range fields {
			if fields[i] != serie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SerieQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(serie.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = serie.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SerieGroupBy is the group-by builder for Serie entities.
type SerieGroupBy struct {
	selector
	build *SerieQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SerieGroupBy) Aggregate(fns ...AggregateFunc) *SerieGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SerieGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SerieQuery, *SerieGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SerieGroupBy) sqlScan(ctx context.Context, root *SerieQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SerieSelect is the builder for selecting fields of Serie entities.
type SerieSelect struct {
	*SerieQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SerieSelect) Aggregate(fns ...AggregateFunc) *SerieSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SerieSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SerieQuery, *SerieSelect](ctx, ss.SerieQuery, ss, ss.inters, v)
}

func (ss *SerieSelect) sqlScan(ctx context.Context, root *SerieQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
