// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mangaweb4/mangaweb4-backend/ent/predicate"
	"github.com/mangaweb4/mangaweb4-backend/ent/tag"
	"github.com/mangaweb4/mangaweb4-backend/ent/taguser"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// TagUserQuery is the builder for querying TagUser entities.
type TagUserQuery struct {
	config
	ctx        *QueryContext
	order      []taguser.OrderOption
	inters     []Interceptor
	predicates []predicate.TagUser
	withTag    *TagQuery
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TagUserQuery builder.
func (tuq *TagUserQuery) Where(ps ...predicate.TagUser) *TagUserQuery {
	tuq.predicates = append(tuq.predicates, ps...)
	return tuq
}

// Limit the number of records to be returned by this query.
func (tuq *TagUserQuery) Limit(limit int) *TagUserQuery {
	tuq.ctx.Limit = &limit
	return tuq
}

// Offset to start from.
func (tuq *TagUserQuery) Offset(offset int) *TagUserQuery {
	tuq.ctx.Offset = &offset
	return tuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tuq *TagUserQuery) Unique(unique bool) *TagUserQuery {
	tuq.ctx.Unique = &unique
	return tuq
}

// Order specifies how the records should be ordered.
func (tuq *TagUserQuery) Order(o ...taguser.OrderOption) *TagUserQuery {
	tuq.order = append(tuq.order, o...)
	return tuq
}

// QueryTag chains the current query on the "tag" edge.
func (tuq *TagUserQuery) QueryTag() *TagQuery {
	query := (&TagClient{config: tuq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taguser.Table, taguser.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taguser.TagTable, taguser.TagColumn),
		)
		fromU = sqlgraph.SetNeighbors(tuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (tuq *TagUserQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: tuq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taguser.Table, taguser.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taguser.UserTable, taguser.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(tuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TagUser entity from the query.
// Returns a *NotFoundError when no TagUser was found.
func (tuq *TagUserQuery) First(ctx context.Context) (*TagUser, error) {
	nodes, err := tuq.Limit(1).All(setContextOp(ctx, tuq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{taguser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tuq *TagUserQuery) FirstX(ctx context.Context) *TagUser {
	node, err := tuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TagUser ID from the query.
// Returns a *NotFoundError when no TagUser ID was found.
func (tuq *TagUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tuq.Limit(1).IDs(setContextOp(ctx, tuq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{taguser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tuq *TagUserQuery) FirstIDX(ctx context.Context) int {
	id, err := tuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TagUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TagUser entity is found.
// Returns a *NotFoundError when no TagUser entities are found.
func (tuq *TagUserQuery) Only(ctx context.Context) (*TagUser, error) {
	nodes, err := tuq.Limit(2).All(setContextOp(ctx, tuq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{taguser.Label}
	default:
		return nil, &NotSingularError{taguser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tuq *TagUserQuery) OnlyX(ctx context.Context) *TagUser {
	node, err := tuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TagUser ID in the query.
// Returns a *NotSingularError when more than one TagUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (tuq *TagUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tuq.Limit(2).IDs(setContextOp(ctx, tuq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{taguser.Label}
	default:
		err = &NotSingularError{taguser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tuq *TagUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := tuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TagUsers.
func (tuq *TagUserQuery) All(ctx context.Context) ([]*TagUser, error) {
	ctx = setContextOp(ctx, tuq.ctx, ent.OpQueryAll)
	if err := tuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TagUser, *TagUserQuery]()
	return withInterceptors[[]*TagUser](ctx, tuq, qr, tuq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tuq *TagUserQuery) AllX(ctx context.Context) []*TagUser {
	nodes, err := tuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TagUser IDs.
func (tuq *TagUserQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tuq.ctx.Unique == nil && tuq.path != nil {
		tuq.Unique(true)
	}
	ctx = setContextOp(ctx, tuq.ctx, ent.OpQueryIDs)
	if err = tuq.Select(taguser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tuq *TagUserQuery) IDsX(ctx context.Context) []int {
	ids, err := tuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tuq *TagUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tuq.ctx, ent.OpQueryCount)
	if err := tuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tuq, querierCount[*TagUserQuery](), tuq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tuq *TagUserQuery) CountX(ctx context.Context) int {
	count, err := tuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tuq *TagUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tuq.ctx, ent.OpQueryExist)
	switch _, err := tuq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tuq *TagUserQuery) ExistX(ctx context.Context) bool {
	exist, err := tuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TagUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tuq *TagUserQuery) Clone() *TagUserQuery {
	if tuq == nil {
		return nil
	}
	return &TagUserQuery{
		config:     tuq.config,
		ctx:        tuq.ctx.Clone(),
		order:      append([]taguser.OrderOption{}, tuq.order...),
		inters:     append([]Interceptor{}, tuq.inters...),
		predicates: append([]predicate.TagUser{}, tuq.predicates...),
		withTag:    tuq.withTag.Clone(),
		withUser:   tuq.withUser.Clone(),
		// clone intermediate query.
		sql:  tuq.sql.Clone(),
		path: tuq.path,
	}
}

// WithTag tells the query-builder to eager-load the nodes that are connected to
// the "tag" edge. The optional arguments are used to configure the query builder of the edge.
func (tuq *TagUserQuery) WithTag(opts ...func(*TagQuery)) *TagUserQuery {
	query := (&TagClient{config: tuq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tuq.withTag = query
	return tuq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (tuq *TagUserQuery) WithUser(opts ...func(*UserQuery)) *TagUserQuery {
	query := (&UserClient{config: tuq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tuq.withUser = query
	return tuq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TagID int `json:"tag_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TagUser.Query().
//		GroupBy(taguser.FieldTagID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tuq *TagUserQuery) GroupBy(field string, fields ...string) *TagUserGroupBy {
	tuq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TagUserGroupBy{build: tuq}
	grbuild.flds = &tuq.ctx.Fields
	grbuild.label = taguser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TagID int `json:"tag_id,omitempty"`
//	}
//
//	client.TagUser.Query().
//		Select(taguser.FieldTagID).
//		Scan(ctx, &v)
func (tuq *TagUserQuery) Select(fields ...string) *TagUserSelect {
	tuq.ctx.Fields = append(tuq.ctx.Fields, fields...)
	sbuild := &TagUserSelect{TagUserQuery: tuq}
	sbuild.label = taguser.Label
	sbuild.flds, sbuild.scan = &tuq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TagUserSelect configured with the given aggregations.
func (tuq *TagUserQuery) Aggregate(fns ...AggregateFunc) *TagUserSelect {
	return tuq.Select().Aggregate(fns...)
}

func (tuq *TagUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tuq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tuq); err != nil {
				return err
			}
		}
	}
	for _, f := range tuq.ctx.Fields {
		if !taguser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tuq.path != nil {
		prev, err := tuq.path(ctx)
		if err != nil {
			return err
		}
		tuq.sql = prev
	}
	return nil
}

func (tuq *TagUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TagUser, error) {
	var (
		nodes       = []*TagUser{}
		_spec       = tuq.querySpec()
		loadedTypes = [2]bool{
			tuq.withTag != nil,
			tuq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TagUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TagUser{config: tuq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tuq.withTag; query != nil {
		if err := tuq.loadTag(ctx, query, nodes, nil,
			func(n *TagUser, e *Tag) { n.Edges.Tag = e }); err != nil {
			return nil, err
		}
	}
	if query := tuq.withUser; query != nil {
		if err := tuq.loadUser(ctx, query, nodes, nil,
			func(n *TagUser, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tuq *TagUserQuery) loadTag(ctx context.Context, query *TagQuery, nodes []*TagUser, init func(*TagUser), assign func(*TagUser, *Tag)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TagUser)
	for i := range nodes {
		fk := nodes[i].TagID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tag.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tag_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tuq *TagUserQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*TagUser, init func(*TagUser), assign func(*TagUser, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TagUser)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tuq *TagUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tuq.querySpec()
	_spec.Node.Columns = tuq.ctx.Fields
	if len(tuq.ctx.Fields) > 0 {
		_spec.Unique = tuq.ctx.Unique != nil && *tuq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tuq.driver, _spec)
}

func (tuq *TagUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(taguser.Table, taguser.Columns, sqlgraph.NewFieldSpec(taguser.FieldID, field.TypeInt))
	_spec.From = tuq.sql
	if unique := tuq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tuq.path != nil {
		_spec.Unique = true
	}
	if fields := tuq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taguser.FieldID)
		for i := range fields {
			if fields[i] != taguser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tuq.withTag != nil {
			_spec.Node.AddColumnOnce(taguser.FieldTagID)
		}
		if tuq.withUser != nil {
			_spec.Node.AddColumnOnce(taguser.FieldUserID)
		}
	}
	if ps := tuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tuq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tuq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tuq *TagUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tuq.driver.Dialect())
	t1 := builder.Table(taguser.Table)
	columns := tuq.ctx.Fields
	if len(columns) == 0 {
		columns = taguser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tuq.sql != nil {
		selector = tuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tuq.ctx.Unique != nil && *tuq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tuq.predicates {
		p(selector)
	}
	for _, p := range tuq.order {
		p(selector)
	}
	if offset := tuq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tuq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TagUserGroupBy is the group-by builder for TagUser entities.
type TagUserGroupBy struct {
	selector
	build *TagUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tugb *TagUserGroupBy) Aggregate(fns ...AggregateFunc) *TagUserGroupBy {
	tugb.fns = append(tugb.fns, fns...)
	return tugb
}

// Scan applies the selector query and scans the result into the given value.
func (tugb *TagUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tugb.build.ctx, ent.OpQueryGroupBy)
	if err := tugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TagUserQuery, *TagUserGroupBy](ctx, tugb.build, tugb, tugb.build.inters, v)
}

func (tugb *TagUserGroupBy) sqlScan(ctx context.Context, root *TagUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tugb.fns))
	for _, fn := range tugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tugb.flds)+len(tugb.fns))
		for _, f := range *tugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TagUserSelect is the builder for selecting fields of TagUser entities.
type TagUserSelect struct {
	*TagUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tus *TagUserSelect) Aggregate(fns ...AggregateFunc) *TagUserSelect {
	tus.fns = append(tus.fns, fns...)
	return tus
}

// Scan applies the selector query and scans the result into the given value.
func (tus *TagUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tus.ctx, ent.OpQuerySelect)
	if err := tus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TagUserQuery, *TagUserSelect](ctx, tus.TagUserQuery, tus, tus.inters, v)
}

func (tus *TagUserSelect) sqlScan(ctx context.Context, root *TagUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tus.fns))
	for _, fn := range tus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
